customize docker plugin
carbynestack/amphora pull request #23
Opened 2022-03-14 16:56 UTC by grafjo

2022-03-15 10:56 UTC, strieflin requested changes
The changes in formatting (new lines in imports and reformatting of comment) are artifacts of not using `pre-commit`. Please adhere to the [developer guide](https://github.com/carbynestack/carbynestack/blob/master/DEVELOPING.md) for instructions how to set it up correctly. This is a prerequisite for any PR to be accepted (FYI: @sbckr).

2022-03-15 13:48 UTC, grafjo commented
> The changes in formatting (new lines in imports and reformatting of comment) are artifacts of not using `pre-commit`. Please adhere to the [developer guide](https://github.com/carbynestack/carbynestack/blob/master/DEVELOPING.md) for instructions how to set it up correctly. This is a prerequisite for any PR to be accepted (FYI: @sbckr).

thx for the feedback - solved those issues!

2022-03-15 15:10 UTC, strieflin requested changes

2022-03-17 09:26 UTC, grafjo commented on amphora-service/pom.xml
> +        <docker.repository>ghcr.io/carbynestack/${project.artifactId}</docker.repository>
requested change is done

2022-03-18 08:59 UTC, strieflin approved these changes
LGTM

2022-03-18 09:04 UTC, merged