Fix vulnerabilities
carbynestack/amphora pull request #44
Opened 2023-03-01 13:52 UTC by sbckr

2023-03-01 14:07 UTC, sbckr commented
cannot tell reasons for the codecov check to fail, but its own report sais coverage has increased:

> # [Codecov](https://codecov.io/gh/carbynestack/amphora/pull/44?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=carbynestack) Report
> 
> > Merging [#44](https://codecov.io/gh/carbynestack/amphora/pull/44?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=carbynestack) ([0159659](https://github.com/carbynestack/amphora/commit/015965900d7ab52fee0ee71a028ac85d4d425cf4)) into [master](https://codecov.io/gh/carbynestack/amphora/commit/2fa009a8b689cc2345a39ed6bbde268d6e9b4f09?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=carbynestack) ([2fa009a](https://github.com/carbynestack/amphora/commit/2fa009a8b689cc2345a39ed6bbde268d6e9b4f09)) will **increase** coverage by `51.22%`.

2023-03-01 14:46 UTC, sbckr commented
E2E tests successful

2023-03-01 14:48 UTC, sbckr commented
Blocked by carbynestack/castor#48 to upgrade castor version

2023-03-03 07:22 UTC, strieflin requested changes
Found some smaller issues, only (see other comments).

2023-03-03 07:22 UTC, strieflin commented on amphora-common/src/test/java/io/carbynestack/amphora/common/entities/SecretShareTest.java
> +  void givenTwoSecretShareWithSameContent_whenCompareEqual_thenMatch() {
Typo: Share**s**

2023-03-03 07:22 UTC, strieflin commented on amphora-java-client/src/test/java/io/carbynestack/amphora/client/DefaultAmphoraClientTest.java
> +  void givenOutPutDeliveryObjectsOfVariousSize_whenDownloadingObject_thenReturnExpectedContent() {
Typo: Out**p**ut

2023-03-03 07:22 UTC, strieflin commented on amphora-java-client/src/test/java/io/carbynestack/amphora/client/DefaultAmphoraInterVcpClientTest.java
> +  void givenNoServiceUriDefined_whenBuildingInterVcClient_thenThrowException() {
Type: InterVc*p*Client

2023-03-03 07:22 UTC, strieflin commented on amphora-service/src/test/resources/application-test.properties
> +spring.config.activate.on-profile=test
Missing license header. Please also check for rest of codebase.

2023-03-03 09:11 UTC, strieflin approved these changes
LGTM

2023-03-03 09:12 UTC, merged